### PR TITLE
Fix str issue

### PR DESCRIPTION
**Pull request by loiccoyle**
Hi,
I was having some issues with pytimber, I was getting the following error message:
```
File "/afs/cern.ch/work/l/lcoyle/public/pylossmap/src/pytimber/pytimber/pytimber.py", line 624, in get
", ".join(logvars)
TypeError: sequence item 0: expected str instance, cern.accsoft.cals.extr.domain.core.metadata.Variable found
```
For some reason the items in the `variables` java lists are no longer strings, so I added a few  `.toString()` calls and it seems to have fixed it.

I was getting another related error:
```
jvar = variables.getVariable(v)
TypeError: No matching overloads found for cern.accsoft.cals.extr.domain.core.metadata.VariableSet.getVariable(cern.accsoft.cals.extr.domain.core.metadata.Variable), options are:
	public cern.accsoft.cals.extr.domain.core.metadata.Variable cern.accsoft.cals.extr.domain.core.metadata.VariableSet.getVariable(java.lang.String)
	public cern.accsoft.cals.extr.domain.core.metadata.Variable cern.accsoft.cals.extr.domain.core.metadata.VariableSet.getVariable(int)
```
adding `v = v.toString()` before the `getVariable` call seems to have fixed it.

### CODE REVIEW

**Comment by thytterdal** [comment]
Hi, I had the same issue a while ago. 

The issue is caused by the `startJVM` function in `jpype` 0.7.2 ignoring the `convertStrings` option which was introduced in version 0.7 (which is set to `True` by `cmmnbuild_dep_manager` if the `Jpype` version is `>=0.7`). 

According to the changelog, the default behavior should be to cast java strings to python string without even specifying this flag until version 0.8 (unreleased), so it seems like something is wrong in the latest release.

If you pin your Jpype1 version to "<=0.7.1" it should solve the issue.

**Comment by loiccoyle** [comment]
Thanks a lot for the info, I can confirm when using `JPype1==0.7.1` the issue is not present.
I leave it up to @rdemaria to decide what to do with this PR.

**Comment by rdemaria** [comment]
Is there any related issue in jpype?

**Comment by rdemaria** [comment]
@loiccoyle  are the test passing with this fix?

**Comment by rdemaria** [comment]
Ok, this fix break with 0.7.1... I try to see if there is a way to support both 0.7.1 and 0.7.2...

**Comment by thytterdal** [comment]
There is no issue open with jpype. I will open one.

**Comment by thytterdal** [comment]
https://github.com/jpype-project/jpype/issues/664

**Comment by rdemaria** [comment]
I think the problems is that when iterating on the VariableSet jpype 0.7.1 returns strings while 0.7.2 returns Variable objects

**Comment by loiccoyle** [comment]
> Ok, this fix break with 0.7.1... I try to see if there is a way to support both 0.7.1 and 0.7.2...

FYI, I found that changing `v.toString()` to `str(v)` works for both JPype1 0.7.2 and 0.7.1, but now, I think due to 85740e3df6eea974369d6ba14025619c07e2b396, there is other stuff breaking for 0.7.1.
```
File "/afs/cern.ch/work/l/lcoyle/public/pylossmap/src/pytimber/tests/test_loggingdb.py", line 15, in test_search
    variables = ldb.search("HX:BETA%")
File "/afs/cern.ch/work/l/lcoyle/public/pylossmap/src/pytimber/pytimber/pytimber.py", line 214, in search
    return [vv.getVariableName() for vv in vl]
File "/afs/cern.ch/work/l/lcoyle/public/pylossmap/src/pytimber/pytimber/pytimber.py", line 214, in <listcomp>
    return [vv.getVariableName() for vv in vl]
AttributeError: 'str' object has no attribute 'getVariableName'
```

**Comment by rdemaria** [comment]
Can you try if  vv.getVariableName() ->  str(vv) works as well in both versions?

**Comment by loiccoyle** [comment]
I tried  `vv.getVariableName()` -> `str(vv)` and indeed it did fix that error, for both 0.7.1 & 0.7.2, only to reveal others for 0.7.1.
This is the output when I try to run the tests (with the added `tests/run_tests.py`), in this branch: [fix_str_2](https://github.com/loiccoyle/pytimber/tree/fix_str_2)

```python
Running test_search
Running test_get_simple
INFO:pytimber.pytimber:List of variables to be queried: HX:FILLN
INFO:pytimber.pytimber:Retrieved 6 values for HX:FILLN
Running test_getVariable
INFO:pytimber.pytimber:List of variables to be queried: HX:FILLN
INFO:pytimber.pytimber:Retrieved 6 values for HX:FILLN
Running test_get_unixtime
INFO:pytimber.pytimber:List of variables to be queried: HX:FILLN
INFO:pytimber.pytimber:Retrieved 6 values for HX:FILLN
Running test_get_vectornumeric
INFO:pytimber.pytimber:List of variables to be queried: LHC.BQBBQ.CONTINUOUS_HS.B1:ACQ_DATA_H
INFO:pytimber.pytimber:Retrieved 1 values for LHC.BQBBQ.CONTINUOUS_HS.B1:ACQ_DATA_H
Running test_get_vectorstring
INFO:pytimber.pytimber:List of variables to be queried: LHC.BOFSU:BPM_NAMES_H
INFO:pytimber.pytimber:Retrieved 1 values for LHC.BOFSU:BPM_NAMES_H
Running test_getScaled
INFO:pytimber.pytimber:List of variables to be queried: MSC01.ZT8.107:COUNTS
INFO:pytimber.pytimber:Retrieved 3 values for MSC01.ZT8.107:COUNTS
Running test_Timestamp
ERROR:__main__:Failure
ERROR:__main__:
Traceback (most recent call last):
  File "run_tests.py", line 10, in try_run
    func()
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/tests/test_loggingdb.py", line 110, in test_Timestamp
    == "Oct 12, 2015 12:12:32 PM"
AssertionError
Running test_hierarchy
Running test_getUnit
ERROR:__main__:Failure
ERROR:__main__:'str' object has no attribute 'getUnit'
Traceback (most recent call last):
  File "run_tests.py", line 10, in try_run
    func()
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/tests/test_loggingdb.py", line 119, in test_getUnit
    units = ldb.getUnit("%:LUMI_TOT_INST")
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/pytimber/pytimber.py", line 221, in getUnit
    for vv in self.getVariableSet(pattern)
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/pytimber/pytimber.py", line 221, in <listcomp>
    for vv in self.getVariableSet(pattern)
AttributeError: 'str' object has no attribute 'getUnit'
Running test_getDescription
ERROR:__main__:Failure
ERROR:__main__:'str' object has no attribute 'getDescription'
Traceback (most recent call last):
  File "run_tests.py", line 10, in try_run
    func()
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/tests/test_loggingdb.py", line 124, in test_getDescription
    units = ldb.getDescription("%:LUMI_TOT_INST")
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/pytimber/pytimber.py", line 212, in getDescription
    for vv in self.getVariableSet(pattern)
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/pytimber/pytimber.py", line 212, in <listcomp>
    for vv in self.getVariableSet(pattern)
AttributeError: 'str' object has no attribute 'getDescription'
Running test_fundamentals
INFO:pytimber.pytimber:List of variables to be queried: CPS.TGM:USER
INFO:pytimber.pytimber:Querying fundamentals (pattern: CPS:%:SFTPRO%):
INFO:pytimber.pytimber:List of fundamentals found: CPS:MTE_OP:SFTPRO2, CPS:SFTPRO_CT:SFTPRO1
INFO:pytimber.pytimber:Retrieved 4 values for CPS.TGM:USER
Running test_getStats
INFO:pytimber.pytimber:List of variables to be queried: LHC.BOFSU:EIGEN_FREQ_2_B1
Running test_getMetaData
ERROR:__main__:Failure
ERROR:__main__:No matching overloads found for com.sun.proxy.$Proxy2.getVectorElements(str), options are:
	public final cern.accsoft.cals.extr.domain.core.metadata.VectornumericElementsSet com.sun.proxy.$Proxy2.getVectorElements(cern.accsoft.cals.extr.domain.core.metadata.Variable)

	at findOverload(native/common/jp_method.cpp:242)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:167)
Traceback (most recent call last):
  File "run_tests.py", line 10, in try_run
    func()
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/tests/test_loggingdb.py", line 152, in test_getMetaData
    out = ldb.getMetaData(var)
  File "/afs/cern.ch/work/l/lcoyle/public/pytimber/pytimber/pytimber.py", line 904, in getMetaData
    variable
TypeError: No matching overloads found for com.sun.proxy.$Proxy2.getVectorElements(str), options are:
	public final cern.accsoft.cals.extr.domain.core.metadata.VectornumericElementsSet com.sun.proxy.$Proxy2.getVectorElements(cern.accsoft.cals.extr.domain.core.metadata.Variable)

	at findOverload(native/common/jp_method.cpp:242)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:167)
```
The tests are successful for 0.7.2

**Comment by rdemaria** [comment]
(You can use pytest to run the tests, just ./pytest )

**Comment by rdemaria** [comment]
The problem is that

list(cals.getVariableSet("LHC.BOFSU:BPM_NAMES_H"))

gives a list of string in 0.7.1 and list of Variables in 0.7.2

It looks like:

list(cals.getVariableSet("LHC.BOFSU:BPM_NAMES_H").getVariables())

gives a list of variables for both versions.

Can you confirm?

**Comment by loiccoyle** [comment]
> (You can use pytest to run the tests, just ./pytest )

Oh nice I didn't realize pytest was that smart.

> Can you confirm?

Yes I got the same behaviour.

**Comment by rdemaria** [comment]
I think I fixed everything with 3f4b24076cd9469f12faee904275827643365e91

**Comment by loiccoyle** [comment]
:+1: perfect !

**Pull request merged**
