### PR TITLE
added getScaled() 

### PR DESCRIPTION
**Pull request by kin94der**
adds the getScaled() function to use the scaling functions provided by CALS API.
An example is added to PyTimber_Tutorial notebook

### CODE REVIEW

**Comment by rdemaria** [comment]
Have you tried to test it in both Python2 and Python3? Can you also increase the version number in __init__.py?

**Comment by rdemaria** [comment]
I would also use scaleAlgorithm, scaleInterval  for the option to be consistent with the names in the command line tool and scaleTime already used

**Comment by kin94der** [comment]
I edited the paramaters as you suggested and updated the example in PyTimber_Tutorial.ipynb.
I also added a test in test_ldb.py
Should I update to 2.4.0 or 2.3.5?

**Comment by rdemaria** [comment]
2.4.0 is good, we try to comply with this: http://semver.org/

Please also add your name in the authors!

**Pull request merged**
