### PR TITLE
fix emittance calculation in BSRT

### PR DESCRIPTION
**Pull request by mfittere**
I fixed some bugs for the LSF,BETA and ENERGY values extracted in order to calculate the emittances. Please merge this version as soon as possible.

### CODE REVIEW

**Comment by rdemaria** [comment]
Is the change in axis formatter really needed? Could you implement as an option?

**Comment by mfittere** [comment]
No, it is not needed. I can implement it as an option. Do you really want all these .000 ???

**Comment by rdemaria** [comment]
Not necessarily, but there are some high frequency data for which it makes
sense to go inside the seconds. Perhaps we could check the extent of the
data (e.g. bigger than 20 seconds) and decide accordingly which string to
put.

**Comment by mfittere** [comment]
I think that would be good! Because I am actually annoyed by always having these big data labels. We could have an auto mode where it looks for the range of the data and a user defined mode, where you can explicitly give the date string?

**Comment by rdemaria** [comment]
If you are ok with it I can merge, let me know...

**Pull request merged**
