### PR TITLE
LHCBSRT & LHCBWS rework

### PR DESCRIPTION
**Pull request by loiccoyle**
LHCBSRT.py:
* Hard coded the variable names instead of doing multiple calls to search for them
* `_get_timber_data` outputs to Dataframe
* reworked `_timber_to_emit` for DataFrame format, speed improvement
* added flag 'use_dataframe' to `_timber_to_emit` select the output format, either:
  * the original dict --> structured array (default)
  * MultiIndex DataFrame (this format breaks the fitting and plotting methods)

LHCBWS.py:
* Separated the gaussian fitting from the data fetching
* Hard coded the variable names instead of doing multiple calls to search for them
* Added 'convert_gate' flag to `_get_timber_data`, to control whether to convert the LHC.BWS.5%NGATE data to slot numbers
*  Changed output of `_timber_to_dict` to output a MultiIndex DataFrame of the compatible data and a dict --> structured arrays (the original data format) for the rest
* Rewrote the `update_beta_energy` for compatibility with new format, significant speed improvement

toolbox.py:
* PEP8 compliance

dataquery.py:
* PEP8 compliance

Added BWSExample.ipynb to provide some example usage of LHCBWS.py

### CODE REVIEW

**Comment by rdemaria** [comment]
`import pytimber` does not look right, shouldn't we use `from .  import pytimber` ?

**Comment by loiccoyle** [comment]
The `import pytimber` was there before I started the branch, but I think you are right, I will change it.

**Comment by loiccoyle** [comment]
Ok, I will drop the old dict of structured arrays in LHCBSRT and reimplement the fitting and plotting for DataFrames.

**Comment by loiccoyle** [comment]
The fitting and the plotting are working now.

**Comment by rdemaria** [comment]
Can you update the changelog and bump the version as well (maybe 2.7.1 is still ok...)?

**Comment by loiccoyle** [comment]
I would like to have your opinion, for the LHCBSRT data the output format is indexed with slot then time

| | | sigh | sigv | lsfh | lsfv | beth | betv | emith | emitv | energy |
|---|---|---|---|---|---|---|---|---|---|---|
| slots | time |

But the LHCBWS I indexed it time then slot:

|  |  | gain |egev | beta | emit |
|---|---|---|---|---|---|
| time | slot |

I did it like this because for BSRT data there can easily be fewer slots than timestamps whereas for BWS data there typically is timestamps than slots. However perhaps for consistency I should index them the same ?

**Comment by rdemaria** [comment]
Have you tried to run the tests in the test directory? If there is no problem I can merge and release.

**Comment by loiccoyle** [comment]
I have tried running the tests but I don't think they are up to date. Even with the master branch I get failures. But at least I get the same errors in the master branch and this PR...

**Comment by rdemaria** [comment]
Most definitely not up to date... I merge, do some tests in case release...

**Pull request merged**
