### PR TITLE
Added _ to Hierarchy method names

### PR DESCRIPTION
**Pull request by levens**
Added a _ to Hierarchy method names so that they do not get shown in the
suggestions.

### CODE REVIEW

**Comment by rdemaria** [comment]
In principle they should not be visible in the suggestions, since there is the __dir__ method. In which context do you see them?

**Comment by levens** [comment]
Hi Riccardo,

I see them in the tab completion in the python interpreter:

```
[tlevens@lxplus009] ~ $ python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytimber
>>> ldb = pytimber.LoggingDB()
>>> ldb.tree.
ldb.tree.ADE               ldb.tree.GCS               ldb.tree.MCS               ldb.tree.TestLab
ldb.tree.ATLAS             ldb.tree.get_vars(         ldb.tree.NA62              ldb.tree.TI2
ldb.tree.AWAKE             ldb.tree.HIE               ldb.tree.nTOF              ldb.tree.TI8
ldb.tree.cleanName(        ldb.tree.HiRadMat          ldb.tree.PS                ldb.tree.TIM_by_LOCATION
ldb.tree.CMS               ldb.tree.ISOLDE            ldb.tree.PSB               ldb.tree.TIM_by_SYSTEM
ldb.tree.CNGS              ldb.tree.LEIR              ldb.tree.PSEN              ldb.tree.TT10
ldb.tree.CRYO              ldb.tree.LHC               ldb.tree.QPS               ldb.tree.TT2
ldb.tree.CTF3              ldb.tree.LHC_HWC           ldb.tree.SM18              ldb.tree.TT20
ldb.tree.CV                ldb.tree.LIFTS             ldb.tree.SPS               ldb.tree.TT40
ldb.tree.Detector_cooling  ldb.tree.Linac_2           ldb.tree.SPS_EA            ldb.tree.TT60
ldb.tree.EAST_HALL         ldb.tree.LINAC2            ldb.tree.SURVEY            ldb.tree.VAC
ldb.tree.ENS               ldb.tree.LINAC3            ldb.tree.SYSTEM            ldb.tree.WIC
ldb.tree.Environment       ldb.tree.LINAC4            ldb.tree.SYSTEM_TEST       
ldb.tree.Fundamental_Data  ldb.tree.LN4TS             ldb.tree.TEST              
>>> ldb.tree.
```

Cheers,

**Comment by rdemaria** [comment]
The python3 completion use dir() on both the instance and the class, differently from ipython. Funny thing is that ipython in your afs installation (5.1.0) crashes the JVM on ldb.tree.<TAB>, while an old version does not... (investigating...)

**Comment by levens** [comment]
Hi Riccardo,

Yes, I noticed the crash as well... I'm not sure why either...

Cheers,

**Pull request merged**
