### PR TITLE
Multiprocessing  branch

### PR DESCRIPTION
**Pull request by chernals**
Hi Riccardo.

I've been worked on some parallelisation, in a nutshell it goes down to:
- IO bound tasks are correctly parallelizated with multithreading in Python, and jpype is perfectly able to handle that. Now the queries to timber are done in parallel
- CPU bound taks are totally not suitable for multithreading in python due to the GIL. I adopted another yet related approach: multiprocessing which as a very similar structure. Note that this is not negligible because a lot of time is spent unpacking the java objects and casting them into python types. Its ever slower when we process the timestamps (which get does for all variables but get aligned does only for the master variable)

Anyway I kept the interface exactly identically so they can be checkout and measured.

### CODE REVIEW

**Comment by rdemaria** [comment]
Many thanks! The pull request has conflicts. Can you see what is the problem?

**Comment by levens** [comment]
Hi Riccardo,

I guess Cedric needs to manually merge in the changes from my PR.

Cheers,

**Comment by chernals** [comment]
I wouldn't merge this branch in master, it works, I use it, but it's a bit experimental.

**Comment by levens** [comment]
Hi Cedric,

Why not merge it into rdemaria:multiprocessing instead of rdemaria:master?

Cheers,

**Comment by rdemaria** [comment]
I  am not sure if this is still relevant. If it is the case, please reopen.

**Pull request closed without merging**
