### PR TITLE
Fix bug with unix time and daylight saving times

### PR DESCRIPTION
**Pull request by xbuffat**
Avoid double convertion of unix timestamp to string to java timestamp to remove bug with daylight saving times

### CODE REVIEW

**Comment by rdemaria** [comment]
Have you tested it with Python 3?

**Comment by xbuffat** [comment]
No, I didn't. I don't have a working version of jpype for python3...

**Comment by rdemaria** [comment]
You can use:
/afs/cern.ch/work/t/tlevens/public/python/anaconda3/

**Comment by rdemaria** [comment]
Can you also increase the version number (last value)?

**Comment by levens** [comment]
Hi Riccardo, Xavier,

Seems OK for me under Python 3. I would suggest to merge before the next release.

Cheers,

**Comment by rdemaria** [comment]
I cannot remember now but there was still an issue. I will try to dig as
soon as  I am back. Do we have sufficient tests? Times are always tricky...

**Pull request merged**
