### PR TITLE
Require cmmnbuild_dep_manager

### PR DESCRIPTION
**Pull request by levens**
New version which requires cmmnbuild_dep_manager, which removes some duplicate code and the local copy of the jars. 

The initialisation of the JVM has been moved to the `LoggingDB.__init__()` function to allow installation without the local jars.

### CODE REVIEW

**Comment by rdemaria** [comment]
Few questions and comments:

Why did you remove Stat from the module? You would create a new class every time you call getStats.

Can't we just put the version number in setup.py instead of parsing python?

`six` is an external package, we should add it to the dependencies, as well as matplotlib and perhaps few others...

For the download links have you tried with

https://gitlab.cern.ch/scripting-tools/cmmnbuild-dep-manager/repository/archive.zip?ref=master#egg=cmmnbuild-dep-manager-1.2.9

or 

http://github.cern.ch/levens/cmmnbuild-dep-manager/tarball/master#egg=cmmnbuild-dep-manager-1.2.9

**Comment by levens** [comment]
> Why did you remove Stat from the module? You would create a new class every time you call getStats.

Yeah, you are probably right -- I have moved it back with the latest commit.

> Can't we just put the version number in setup.py instead of parsing python?

We could do, but then you cannot access it with `pytimber.__version__`, which is recommended by [PEP396](https://www.python.org/dev/peps/pep-0396/). This seems to be the way that most packages handle it. It's strange that there is not a cleaner way...

> six is an external package, we should add it to the dependencies, as well as matplotlib and perhaps few others...

I thought that six was included in the distribution -- it is installed by default on any version of python I have used (including the SLC default version). But maybe it isn't. Of course we can add it. We should also add numpy I guess -- but I removed it after our phone call the other day.

**Comment by chernals** [comment]
Hey guys

Not sure if adding lots of deps is a good idea. Especially matolotlib which is not the nicest package there is.

If we have plotting should it be separated from the main package ?



On 17 Jun 2016, at 02:13, Tom Levens <notifications@github.com<mailto:notifications@github.com>> wrote:


Why did you remove Stat from the module? You would create a new class every time you call getStats.

Yeah, you are probably right -- I have moved it back with the latest commit.

Can't we just put the version number in setup.py instead of parsing python?

We could do, but then you cannot access it with pytimber.__version__, which is recommended by PEP396<https://www.python.org/dev/peps/pep-0396/>. This seems to be the way that most packages handle it. It's strange that there is not a cleaner way...

six is an external package, we should add it to the dependencies, as well as matplotlib and perhaps few others...

I thought that six was included in the distribution -- it is installed by default on any version of python I have used (including the SLC default version). But maybe it isn't. Of course we can add it. We should also add numpy I guess -- but I removed it after our phone call the other day.

**Comment by rdemaria** [comment]
Hello,

in setup.py

dependency_links=[
        'https://gitlab.cern.ch/scripting-tools/cmmnbuild-dep-manager/repository/archive.zip?ref=master#egg=cmmnbuild-dep-manager-1.2.9'
    ]

works for me provided one uses `pip ... --process-dependency-links`. Can you try?

The option is deprecated, but the alternative mechanism in PEP 508 is not in place yet

If this works reliably, I agree in making the plotting stuff in another package. The reason behind is that I was asked to provide a single instruction installation command for integrating the software in the cvmfs distribution.

**Comment by levens** [comment]
Hmm, strange. I tried that exact syntax the other day and it didn't work. But now it does.

The latest commit adds the `dependency_links` and also does automatic lookup of the current `cmmnbuild_dep_manager` version.

**Pull request merged**
