### PR TITLE
fix lsf unit change

### PR DESCRIPTION
**Pull request by loiccoyle**
here is the quick fix for the geometric emittance I mentioned last week.

For some reason the unit of the lsfh & lsfv data changed from 2018-01-01 onward.

### CODE REVIEW

**Comment by rdemaria** [comment]
Thanks a lot! Can you fix the style issues?

**Comment by loiccoyle** [comment]
The entire LHCBSRT.py file does not respect PEP8... I can pass it through a PEP8 formater if that helps.

**Comment by levens** [comment]
For this PR it would probably be best to just fix the issues on the lines you touch and to submit a full clean-up of the file as a separate PR with no code changes.

**Comment by loiccoyle** [comment]
Only the 2 wide indentations remain, as they are throughout the file

**Comment by rdemaria** [comment]
> For this PR it would probably be best to just fix the issues on the lines you touch and to submit a full clean-up of the file as a separate PR with no code changes.

Ok, if you could do that it would be great. I merge the PR in the meanwhile...

**Pull request merged**
